description: SyncLib is a collection of Communication and Synchronisation libraries, including the hybrid-BSP model.
keywords:
  - C++
  - BSP
  - MPI
  - easy
  - fast
  - HPC
website: 'http://synclib.eu/'
license: MIT
authors:
  - name: Mick van Duijn
    email: m.vanduijn@zefiros.eu
    website: 'https://zefiros.eu/'
  - name: Paul Visscher
    email: p.e.visscher@zefiros.eu
    website: 'https://zefiros.eu/'
  - name: Koen Visscher
    email: k.m.visscher@zefiros.eu
    website: 'https://zefiros.eu/'
development:
  modules:
    - name: Zefiros-Software/Defaults
      version: '@head'
    - name: Zefiros-Software/MPI
      version: '@head'
  public:
    libraries:
      - name: Zefiros-Software/PlotLib
        version: ^2.0.0
      - name: Zefiros-Software/Fmt
        version: ^4.0.0
      - name: Zefiros-Software/Armadillo
        version: '>=8.0.0'
      - name: Zefiros-Software/Json
        version: '^3.0.0'
      - name: Zefiros-Software/Args
        version: '@head'
      - name: Zefiros-Software/cxxopts
        version: '2.0.0'
      - name: Zefiros-Software/MKL
        version: '@head'
        settings:
          backend: sequential
          # backend: tbb

          # # Inherited from arma:
          # blas95: true
          # lapack95: true
      - name: Zefiros-Software/Fs
        version: '@head'
      - name: Zefiros-Software/hwloc
        version: '^2.0.1'
settings:
  enableMPI:
    default: false
    reduce: anyTrue
